# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0emessages.proto\"\xc8\x01\n\x0eOffloadRequest\x12\x32\n\x0crequirements\x18\x01 \x01(\x0b\x32\x1c.OffloadRequest.Requirements\x12\"\n\x04type\x18\x02 \x01(\x0e\x32\x14.OffloadRequest.Type\x1a<\n\x0cRequirements\x12\x0b\n\x03\x63pu\x18\x01 \x01(\x02\x12\x0e\n\x06memory\x18\x02 \x01(\x02\x12\x0f\n\x07latency\x18\x03 \x01(\x02\" \n\x04Type\x12\n\n\x06LAMBDA\x10\x00\x12\x0c\n\x08STANDARD\x10\x01\x62\x06proto3')
)



_OFFLOADREQUEST_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='OffloadRequest.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LAMBDA', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STANDARD', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=187,
  serialized_end=219,
)
_sym_db.RegisterEnumDescriptor(_OFFLOADREQUEST_TYPE)


_OFFLOADREQUEST_REQUIREMENTS = _descriptor.Descriptor(
  name='Requirements',
  full_name='OffloadRequest.Requirements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpu', full_name='OffloadRequest.Requirements.cpu', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='memory', full_name='OffloadRequest.Requirements.memory', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latency', full_name='OffloadRequest.Requirements.latency', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=185,
)

_OFFLOADREQUEST = _descriptor.Descriptor(
  name='OffloadRequest',
  full_name='OffloadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requirements', full_name='OffloadRequest.requirements', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='OffloadRequest.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_OFFLOADREQUEST_REQUIREMENTS, ],
  enum_types=[
    _OFFLOADREQUEST_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=219,
)

_OFFLOADREQUEST_REQUIREMENTS.containing_type = _OFFLOADREQUEST
_OFFLOADREQUEST.fields_by_name['requirements'].message_type = _OFFLOADREQUEST_REQUIREMENTS
_OFFLOADREQUEST.fields_by_name['type'].enum_type = _OFFLOADREQUEST_TYPE
_OFFLOADREQUEST_TYPE.containing_type = _OFFLOADREQUEST
DESCRIPTOR.message_types_by_name['OffloadRequest'] = _OFFLOADREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OffloadRequest = _reflection.GeneratedProtocolMessageType('OffloadRequest', (_message.Message,), dict(

  Requirements = _reflection.GeneratedProtocolMessageType('Requirements', (_message.Message,), dict(
    DESCRIPTOR = _OFFLOADREQUEST_REQUIREMENTS,
    __module__ = 'messages_pb2'
    # @@protoc_insertion_point(class_scope:OffloadRequest.Requirements)
    ))
  ,
  DESCRIPTOR = _OFFLOADREQUEST,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:OffloadRequest)
  ))
_sym_db.RegisterMessage(OffloadRequest)
_sym_db.RegisterMessage(OffloadRequest.Requirements)


# @@protoc_insertion_point(module_scope)
